services:
  mqtt-server:
    image: ghcr.io/everest/everest-demo/mqtt-server:${EVEREST_DEMO_TAG}
    platform: linux/x86_64
    logging:
      driver: none

  manager:
    image: ghcr.io/chrisweissmann/manager:${TAG}
    platform: linux/x86_64
    deploy:
      resources:
        limits:
          cpus: "${EVEREST_MANAGER_CPUS}"
          memory: "${EVEREST_MANAGER_MEMORY}"
    depends_on:
      - mqtt-server
    ports:
      - 9000:9000
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    entrypoint: "tail -f /dev/null"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nodered:
    image: ghcr.io/everest/everest-demo/nodered:${EVEREST_DEMO_TAG}
    depends_on:
      - mqtt-server
    ports:
      - 1880:1880
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/config/config-sil-flow.json
