services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  ocpp-db:
    image: citrineos/postgis:v1.1.0
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: 'citrine'
    healthcheck:
      test: 'pg_isready --username=citrine'
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
  citrine:
    image: ghcr.io/citrineos/citrineos-server:1.1.1
    environment:
      APP_NAME: 'all'
      APP_ENV: 'docker'
      CITRINEOS_UTIL_DIRECTUS_USERNAME: 'admin@citrineos.com'
      CITRINEOS_UTIL_DIRECTUS_PASSWORD: 'CitrineOS!'
    depends_on:
      ocpp-db:
        condition: service_healthy
      amqp-broker:
        condition: service_healthy
      directus:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 9229:9229

  directus:
    image: ghcr.io/chrisweissmann/everest-demo/citrineos-directus:1.1.0
    ports:
      - 8055:8055
    volumes:
      - ./directus-env-config.cjs:/directus/config.cjs
    depends_on:
      ocpp-db:
        condition: service_healthy
    environment:
      APP_NAME: 'all'
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      CONFIG_PATH: '/directus/config.cjs'
      EXTENSIONS_AUTO_RELOAD: 'true'
      EXTENSIONS_CACHE_TTL: '1s'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://directus:8055/server/health || exit 1
      start_period: 15s
      start_interval: 5s
      interval: 15s
      timeout: 15s
      retries: 3
